### ISSUE TITLE
Spam mail not moved to Junk

### ISSUE THREAD

**Issue by joyider** [nodemailer/wildduck#134]
Hello.

Recently started using the WIldDuck ecosystem for our new mail system and we are loving it :)
However we noticed an issue with message redirection to Junk or rather the lack of it.

The mail header does not have the X-RSpamd-Spam header or X-Spam-Status header (Not even the X-SPAM from default config) only:
```
X-Rspamd-Bar: +++++++
X-Rspamd-Report: R_DKIM_ALLOW(-0.2) R_SPF_ALLOW(-0.2) MIME_GOOD(-0.1) MANY_INVISIBLE_PARTS(1) MIME_BASE64_TEXT(0.1) SUBJ_ALL_CAPS(3) DMARC_POLICY_ALLOW(-0.5) MICROSOFT_SPAM(4)
X-Rspamd-Score: 7.1
```
 The config option:
```
[header]
bar = X-Rspamd-Bar
report = X-Rspamd-Report
score = X-Rspamd-Score
spam = X-Rspamd-Spam
```
What exactly does `spam = X-Rspamd-Spam` do? can't seem to find any documentation on that one :)

We get the same behavior from a new installation as well? Not sure if this is a Rspam issue or some of the plugins?

Regards
André

**Comment by andris9** [comment]
Spam routing was recently changed from processing headers to using haraka-rspamd plugin output (and more precisely, the "action" value of Rspamd resolution). Everything related to the rspamd header options only have an effect on the headers injected to message but no effect on how WildDuck routes spam.

So in order to route spam you must:

* have the latest haraka-rspamd plugin (and obviously Rspamd)
* have the latest haraka-wildduck plugin
* when creating users via API either not use `spamLevel` value or set it to 50 or lower

**Comment by joyider** [comment]
Thank you so much for your extremely fast response :) Updated rspamd and the plugins for haraka and wildduck, and like magic it now works as intended.

Best Regards
