### ISSUE TITLE
Auto-create archive folder

### ISSUE THREAD

**Issue by vitalvas** [nodemailer/wildduck#147]
I see - a special folder is used in the code - "Archive".
But when creating a user, the folder is not created.

How can I enable auto-creation of this directory?

**Comment by andris9** [comment]
Archive with a special mailbox tag `\Archive` is not created automatically because WildDuck does not have yet any archiving capabilities which might change in the future. Currently you could just a) create a new user via API and b) run the mailbox creation API endpoint to create a mailbox called Archive yourself.
