### ISSUE TITLE
Mail from wildduck new setup going to spam folder of gmail

### ISSUE THREAD

**Issue by imtiyaz-ideavate** [nodemailer/wildduck#153]
Hello @andris9 

Thank you for such a great product.

I have setup the wildduck mail server on AWS Ec2 runing on ubuntu 16.04. The setup was successful and I am able to send and receive email but the email from my server are marked as spam by gmail.

The SPF, DKIM and RevDNS entries seems to be correct as you can see below

![11](https://user-images.githubusercontent.com/19643788/66264934-3f9cf700-e82b-11e9-8e6c-9924b72332bc.png)

I purchased SSL from goDaddy and put it at location "/etc/wildduck/certs/" with the same name as the name of test certificates from letsencrypt.

Please suggest if I am missing anything.

**Comment by andris9** [comment]
You seem to have everything set up correctly. In this case it does not matter what mail server software you are using as the problem is operational and reputation based, not a software issue. Check out, for example, this article about delivering mail to Gmail: https://help.returnpath.com/hc/en-us/articles/224780827-Gmail-deliverability-best-practices

**Comment by imtiyaz-ideavate** [comment]
@andris9 Thank you for your reply and sharing the link.
