### ISSUE TITLE
AWS Setup

### ISSUE THREAD

**Issue by kierancrowntrt** [nodemailer/wildduck#167]
Has anyone got any experience setting this up using AWS services.

I've been trying to set this up on a Amazon Linux 2 AMI, while using Elasticache for the Redis store and AWS DocumentDB for the MongoDB database.

Does anyone know if this is at all possible as all the install instructions seem to be geared towards a self install script for Ubuntu.

**Comment by andris9** [comment]
It should be possible on theory to use the Amazon provided MongoDB and Redis alternatives even though I have never used these. AWS MongoDB is compatible with an older version of MongoDB but WildDuck does not use the newer features (transactions, change streams) anyway, so there should be no problems. WIldDuck ises lua scripting with Redis, I don't know if this is allowed for Elasticache

**Comment by kierancrowntrt** [comment]
Thanks for the prompt reply, would it be recommended in that case then to spin up a separate EC2 instance just for Redis. In terms of a manual install are there any detailed instructions anywhere. Sorry for the noob questions I have already attempted this but didn't get far. May have misconfigured the Haraka installation.

**Comment by mannyveloso** [comment]
FYI, I'll be doing a standard install on AWS soon, and I'll put the steps up on the wiki.

**Comment by mannyveloso** [comment]
Actually, my install is going to be quite different than a standard install. The basic outline is to containerize WD and the outgoing SMTP server and use Fargate to horizontally scale those. There'll probably be a container with the incoming SMTP server that's also using Fargate to scale. The front-end will be an ALB or NLB with an elastic IP.

The main complication at this point is updating the SSL certs. If IMAP does SSL negotiation directly (without a STARTTLS) I can terminate SSL at the load balancer...but on AWS terminating on the ALB/NLB is more expensive than terminating at the instance level. If I terminate at the WD level I need to update the image every 90 days or so (LetsEncrypt), which is awkward.

If I do the docker-based termination I'll probably have another image (or a lambda)  run the letsencrypt update, stash the new certs in S3, then pull the certs into each container on a timed basis. Or just make a shared volume that all the containers, put the certs on it, then have them reload every day. I'm leaning towards the shared volume because that allows me to centralize the config of all the various pieces parts.

**Comment by louis-lau** [comment]
Could also use Traefik or HAProxy for TLS termination if you don't need to support STARTTLS.

**Comment by mannyveloso** [comment]
True, but I'm trying to implement the cheapest AWS-based solution. That would imply another container or instance. Depending on how many clients a container can handle doing TLS directly by WD might be the best. I'd love to terminate at the load balancer, but the ELB/NLB TLS pricing is outrageous; 3k TLS connections costs as much as 100k TCP connections.

Of course, if my service gets to 3k connections that'd be great!

OTOH, it's only .006 USD per LCU, so if it really can terminate more than a container it might be worth it. Welcome to AWS math. I haven't looked at Fargate pricing yet. I'm not sure if Fargate pricing differentiates between x86 or ARM, but this should run fine on an ARM instance, which'll drive the cost down more.

**Comment by louis-lau** [comment]
> cheapest AWS
I'm not sure those two go together haha

Why not use a cheaper cloud with docker swarm or kubernetes?

**Comment by mannyveloso** [comment]
AWS can be really, really cheap if you do it right. I was running a huge application built with Lambda that ended up costing a few dollars a month.

Storage, memory, compute, and bandwidth are generally the most expensive things in AWS. You can get compute and memory down to near zero with serverless, and in-DB storage isn't that expensive. The bandwidth is always a question, because IMAP clients can be weird. But at least bandwidth should only be charged at the ALB (ie: internal bandwidth is free).

I mean, you could always do it cheaper with a VPC from low-end box, but it'd be more work to make a commercial service offering off of those.

**Comment by louis-lau** [comment]
Sure, but WildDuck isn't serverless. It also takes quite a bit of memory when you also have to run rspamd and virus scanning etc etc. With other cloud providers you get 20TB of bandwidth with each vps. But yeah you're right, it does take a bit of work to set up.

**Comment by mannyveloso** [comment]
It's not serverless, but supposedly Fargate is still cheaper than running dedicated EC2 instances. This is a prototype anyway, because I've only played with WD on a real machine and I need to figure out real costing and utilization.

For reference, here's my draft architecture. I'll probably use datadog for monitoring, since they have in-container monitoring. Not sure what I'll do for log file consolidation yet. I don't like cloudwatch logs for some reason that I don't understand. I suspect the spam stuff will be in the incoming SMTP container, but I haven't looked at that yet.

I wish I could somehow steal that low-end-box bandwidth and apply it to my AWS account!

![Infrastructure-Page-1](https://user-images.githubusercontent.com/10236863/87254691-2455bc80-c439-11ea-8e67-b99e23a392d5.png)

**Comment by louis-lau** [comment]
Nice plan! I guess you could add rspamd to the haraka container. But then the whole point of containers is to have one container per application.

Both WildDuck and ZoneMTA can send their logs to graylog, or elastic search through

**Comment by louis-lau** [comment]
Oh and you're pointing port 465/587 to haraka in that setup, that won't work. Those are submission ports, meaning clients submit there emails there for outbound. So ZoneMTA.

Port 25 (the transmission port) should be pointing to haraka :)

**Comment by mannyveloso** [comment]
Oh, I figured server-to-server delivery was all secure these days. They're really still doing those via insecure transport? That's crazy.

**Comment by louis-lau** [comment]
Oh it is, but it uses STARTTLS on port 25, and allows fallback to unencrypted on port 25.
587 is used in the same way, but for submission instead of transmission.

**Comment by mannyveloso** [comment]
Ugh. It's funny, I ran a service years ago that got blacklisted because port 25 was open. It didn't matter that it didn't support non-TLS access, the port scanners didn't care. Port 25 open? Blacklist. At that point it was just easier to force everyone to 587.

It'll be interesting to see if those blacklist providers got smarter. Maybe the DKIM stuff will help with that.

**Comment by louis-lau** [comment]
Most of the time outbound port 25 is blocked because of spamming. I guess some providers have a rule that will also block inbound, even if unneeded. 😁

**Comment by mannyveloso** [comment]
So, an update - everything is getting split up into containers, and I'll need two more: a webmail one and a dedicated API container. I think I have all the configuration required for the AWS side. There are a bunch of requirements for DocumentDB, ElasticCache (redis), and ECS that I'm working through.

This is all the AWS substrate (VPC, services etc). I'll pull these into a CloudFormation template or Terraform file so that the infrastructure can be pulled up easily. These need to be first because they'll be inputs into the config files.

It's always aggravating that you have to have almost everything set up before anything will work.

It'll also be interesting to see if the ARM instances have acceptable performance. I also have to figure out how to load test this guy so I can measure performance effectively.

**Comment by mannyveloso** [comment]
Updated architecture.

![Infrastructure-Overview](https://user-images.githubusercontent.com/10236863/88319038-736cde80-ccd0-11ea-90c0-528f8016ea17.png)

**Comment by louis-lau** [comment]
Nice! In your diagram port 465 and 587 still point bro haraka instead of ZoneMTA. Also if you wanted the TLS for smtp submission to terminate at the load balancer it would be 465 -> 587. Port 25 does unencrypted and STARTTLS for transmission, port 587 does unencrypted and STARTTLS for submission.

**Comment by mannyveloso** [comment]
Documentation - it's hard!

Broke out the SMTP stuff to be more clear.

![Infrastructure-Overview](https://user-images.githubusercontent.com/10236863/88321324-d3b14f80-ccd3-11ea-919a-165fd0822f5d.png)

**Comment by mannyveloso** [comment]
Sorry for the delay, I did this then got busy on other stuff. Attached is a set of terraform scripts that'll build the background parts of the install. That includes:

- The VPC
- The various subnets and security groups
- Optionally, the DocDB (mongodb) instance
- Optionally, the elasticache (redis) instance
- The ECS service definition
- Optionally, the ECS task for wildduck
- The Application Load Balancer

The options are in start.tf. There's also one variable for the container image URL in ecs-mailserver.tf (need to fix that at some point).

After doing the math, it's probably cheaper and more flexible to make WD into a straight-up EC2 instance, which is why the container stuff is optional. You can also, if you'd like, create your own redis and/or MongoDB as well.

This is a pretty good start to an AWS deployment.
[enviornment.zip](https://github.com/nodemailer/wildduck/files/5374726/enviornment.zip)

**Comment by kierancrown** [comment]
Reviving this old form, I've been MIA for a long while @mannyveloso I see you've done gods work here. Did you ever get anywhere with this?

**Comment by mannyveloso** [comment]
no, by the time I started rolling I got hired into my current position. The stuff needs to be updated to the latest modules etc.
