### ISSUE TITLE
production use?

### ISSUE THREAD

**Issue by mleader1** [nodemailer/wildduck#172]
Hi there,

I've been testing this software for a few days and really loved it, while digging it further, is the mail server used by anyone in production environment?

What would be the performance for 10k user mail accounts estimated at 50G mailbox size each, daily emails roughly around 100k in/out transactions?

Also any plan for webhook implementations?

Many thanks for creating such a beautiful mailserver (I like the convenient Restful API )

**Comment by andris9** [comment]
WildDuck is currently used in production for example by a web hosting company in Estonia, having more than 10k+ users (and close to 10TB of data) hosted on a WildDuck cluster. I don't know about the details of other systems, so I would guess that this is currently the largest installation.

WildDuck is designed to scale but it is easily beaten in performance by Dovecot in a single server setup, so if you are looking for hosting as many users as possible in a single server then you should probably go with Dovecot. If you want to host a large number of users in a cluster of servers then WildDuck would probably be much easier to use - if servers are not able to process all load then you can always add additional servers to the system. 100k email transactions should not be a problem. 50GB mailboxes with IMAP are always problematic, mostly because IMAP clients are not really capable of handling such volumes (especially Outlook), even if the specs say they do. In general, you should test it yourself to see if the system suits you or not.

No current plans for webhooks. You can get user specific changes pushed via [change stream API endpoint](https://api.wildduck.email/#api-Users-GetUpdates) but no global changes. You could though use MongoDB change streams and listen on users or message collection to get global changes even though it might be problematic as the db structure may change.
