### ISSUE TITLE
Sort messages

### ISSUE THREAD

**Issue by ramiroaisen** [nodemailer/wildduck#193]
Hi !
Is there any way to sort messages by sent date instead of insertion order?
If not, can anyone guide me to the source where it could be added, what file?
I'll be glad to make a PR for it
thanks!!

**Comment by andris9** [comment]
what kind of sorting do you mean? POP3? IMAP? API?

**Comment by ramiroaisen** [comment]
> what kind of sorting do you mean? POP3? IMAP? API?

I mean for the http api some like 
```/users/me/mailboxes/{id}/messages?sortby={date}```

**Comment by andris9** [comment]
API sorts messages by IMAP message property [Internal Date](https://tools.ietf.org/html/rfc3501#page-12) in a descending order. In lots of times it equals to insertion order but not always. Sorting by other properties is kind of complicated as there must be a supporting index for that. The largest WildDuck instance has more than 100 000 000 emails stored into the cluster and making queries over these messages with unoptimised indexes is super costly. If you want to sort by dates then make sure that when importing emails to WildDuck then the internal date property gets set correctly, ie when making IMAP APPEND calls then the call would have the otherwise optional date/time string set.
