### ISSUE TITLE
Wildduck does not work. Error: socket hang up

### ISSUE THREAD

**Issue by itabrezshaikh** [nodemailer/wildduck#214]
From the day I have installed, I keep getting this error. 
![wildduck does not work](https://user-images.githubusercontent.com/9974389/82033479-67eead00-96ba-11ea-95e8-29458a779d2d.png)

I tried stackoverflow, also created issue at wildduck webmail but I guess issue is in wildduck. The doc is just api doc inside docs dir. Please help or guide.

**Comment by andris9** [comment]
It should usually mean that the WildDuck daemon itself is either not responding or is not able to respond to API queries because, for example, it can't get a connection to database. You could try connecting to API directly and see if it responds with an error

```
curl localhost:8080/users
```

tailing the wildduck log should also show what is going on. Log file should be at /var/log/wildduck-server/wildduck-server.log

**Comment by sandro971** [comment]
if you use a docker container, dont forget set  "0.0.0.0" as host address into your api.toml file. Your IP can be view as 127.0.0.1 only like that.
Dont forget to mention in your wildduck container yml for ports "127.0.0.1:8080:8080"

(api.toml)
`enabled=true
port=8080
# by default bind to localhost only
host="0.0.0.0"`

**Comment by louis-lau** [comment]
Closing as there's been no follow up by the issue creator.
