### ISSUE TITLE
out of scope but feature related enquiry (CalDAV & CardDAV)

### ISSUE THREAD

**Issue by mleader1** [nodemailer/wildduck#256]
Hi,

thanks for the great project, is there any CalDAV & CardDAV project/implementation suggestion that can be used together with wildduck please?

The question mainly considers the factors of authentication mechanism (sharing/bridging) and db storage etc.

A quick line of comment will be apprecaited!

Thanks

**Comment by andris9** [comment]
Currently there are no plans for CalDav/CardDav. Mostly because these protocols are a bit too heavyweight to implement (not enough manpower currently for larger side-projects) and there are no compatible existing projects. I investigated [Fennel](https://github.com/LordEidi/fennel.js) some time ago but it is unmaintained and has an incompatible license.

**Comment by louis-lau** [comment]
https://github.com/nodemailer/wildduck/issues/218#issuecomment-630735745
