### ISSUE TITLE
Webhooks list

### ISSUE THREAD

**Issue by ramiroaisen** [nodemailer/wildduck#274]
Hello!
Do you have a list of possible webhooks that can be added ?
Example: A webhook when a message cannot be delivered

**Comment by louis-lau** [comment]
Yeah, right here in the code:
https://github.com/nodemailer/wildduck/blob/961111ad7132d87dedabeb96f04d6d40a9d28376/lib/events.js#L11-L39

Webhooks about message delivery would have to be fired from ZoneMTA. Perhaps this could be implemented in the zonemta-wildduck plugin, if the current webhook architecture allows for it. I'm not entirely sure.

**Comment by andris9** [comment]
Webhooks for message events are curently on hold as these might have an impact on performance, main problem would be overloading the job queue when a lot of messages are received or sent.

**Comment by louis-lau** [comment]
What's being used for the queue? Something custom? I know with Bull you can define multiple job queues and apply rate limits to them.

**Comment by andris9** [comment]
> What's being used for the queue? Something custom? I know with Bull you can define multiple job queues and apply rate limits to them.

Webhook jobs are queued in Bull. The problem is if there are too many jobs queueing up and workers are stuck (eg. a firewall misconfiguration blocking and delaying HTTP requests). I've manually purged millions of bull queue jobs from Redis for similar reason. First, queue processing gets super slow (as there are millions of jobs already queued up), next Redis starts to fail as all these jobs take up so much memory that Redis is not able to perform its periodic data dump to disk anymore. Not a fun experience. Probably never happens when running a low usage server but the primary target for WildDuck has more than 100k email accounts and a constant flow of incoming emails.

**Comment by louis-lau** [comment]
Ah, and rate limited jobs still get stored of course. I assume jobs won't be queued if no webhooks exist for that specific event type? In that case it would be up to the sysadmin to determine if redis overflowing is actually a risk.
