### ISSUE TITLE
Are there any cross-region multi-server solutions?

### ISSUE THREAD

**Issue by littleplus** [nodemailer/wildduck#281]
Hello, I want to set up the servers in multiple region which may be transcontinental and the latency may reach more than 120ms.

I know the MongoDB cluster could do a replication cross region easily, but the Redis, how could it work? 

Could I use different Redis cluster in different region?

I will be appreciated if you could give me some suggestions.

**Comment by louis-lau** [comment]
Heya,

Have you read this?
https://docs.wildduck.email/#/in-depth/operating-wildduck?id=redis-sentinel

**Comment by littleplus** [comment]
@louis-lau Yes, I have read it, but I have some questions.
1. If I make the redis cluster cross region, does the high latency slow down the read/write to redis? Because the redis has better latency requirements than mongodb.
2. from 1. We know that redis is mainly used as a cache, so if the latency of redis spikes, will the application get much slower or even stuck?
3. Sentinel is used as a sentry for master-slave switching on redis. But if both servers across geographies receive mail, the need should be for master-master synchronization, right?

**Comment by littleplus** [comment]
Or, do you mean this?
```
WildDuck does not store critical information in Redis, so even if some data loss occurs, it should not be noticeable.
```

**Comment by louis-lau** [comment]
While I'm not sure about latency issues, yes, there will always be a single master. The same goes for mongodb. This means that even if you have the secondaries in europe and a primary in the US that your customers in europe will still query the US primary. With mongodb you can read from secondaries, but the data would be inconsistent because of the replication lag. That isn't acceptable for email.

Mongodb does make it possible to have seperate shards for different regions, but wildduck doesn't support this. See #156.

If your concern is latency I would recommend setting up seperate clusters for each region. You could add a smart proxy (like [nginx](https://docs.nginx.com/nginx/admin-guide/mail-proxy/mail-proxy/)) in front of wildduck/zonemta to proxy client connections to the right region. This isn't a wildduck specific strategy, so you should be able to find more online.

**Comment by littleplus** [comment]
ok, I think I get it.

Thank you for your help.
