### ISSUE TITLE
How to stop registering users 

### ISSUE THREAD

**Issue by uhlhosting** [nodemailer/wildduck#317]
Hi,

I did not found any info about locking the registrations on the default home page. 
Also is there some guidelines to customize the interface beside digging the code to look for it.

**Comment by louis-lau** [comment]
Sure! See the wildduck-webmail config:
https://github.com/nodemailer/wildduck-webmail/blob/master/config/default.toml#L14


> customize the interface

What do you mean exactly?

**Comment by uhlhosting** [comment]
> Sure! See the wildduck-webmail config:
> https://github.com/nodemailer/wildduck-webmail/blob/master/config/default.toml#L14
> 
> > customize the interface
> 
> What do you mean exactly?

This is what i meant by interface.
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/6324047/108257681-709b7480-715f-11eb-9015-457fafb48285.png">

**Comment by louis-lau** [comment]
Sorry, I know what you meant by interface. But what do you want to customize?

**Comment by uhlhosting** [comment]
Instead of the screenshots to add another text, and overall the UI/UX.

**Comment by louis-lau** [comment]
There's no way to change the template or css from the configuration, but since it's open source you can just fork the application and change it.

Text: https://github.com/nodemailer/wildduck-webmail/blob/master/views/index.hbs
CSS: https://github.com/nodemailer/wildduck-webmail/tree/master/public/css
