### ISSUE TITLE
Scaling: readiness and liveness endpoints

### ISSUE THREAD

**Issue by nahsi** [nodemailer/wildduck#372]
As I understand wildduck works in active/passive mode when multiple instances are running at the same time.

Is there a way to check which state wildduck is in with HTTP API or TCP? I've looked at [docs](http://docs.wildduck.email/api) and haven't found anything.

Usually software would report its health with liveness endpoint (`/health` for example) and state with rediness (`/ready` for example).

`/health` can be used for monitoring and self-healing, i.e. if it returns anything than `200` workload orchestrator (like Nomad or k8s) can restart it.
`/ready` endpoint can be used to check if it accepts connections (if it is active/master or passive/slave),  for example Consul can resolve DNS record `wildduck.service.consul` to instance that reports `200`.

**Comment by louis-lau** [comment]
> wildduck works in active/passive mode when multiple instances are running at the same time

What exactly do you mean by this?

You're correct. There's no health endpoint at the moment.

**Comment by andris9** [comment]
All WildDuck instances are active, you can run multiple servers and you can connect to any of them with any user (eg. the same user can open multiple IMAP connections and each of these can go to a different WildDuck instance, same goes with API, etc.).
And yes, there is no health check. The best you can do right now is to make a no-op API request, like getting some [setting value](https://docs.wildduck.email/api/#operation/getSetting) and if it responds, then it is healthy, otherwise not.

**Comment by nahsi** [comment]
Oh, I see! When I was testing one instance it responded with 500 and something about being not master in logs, and other was fine so I thought it was active/passive.
But at the time I had issues connecting to mongo due to misconfiguration. I will try again, thank you for your answers and suggestion regarding no-op API request. I will close the issue then since liveness and readiness endpoints are just a convinience in this case.
