### ISSUE TITLE
Backup / Recovery

### ISSUE THREAD

**Issue by ClausMunch** [nodemailer/wildduck#377]
Hi

I was reading through the docs and was wondering, how would a best practice disaster recovery setup be?

Brg,
Claus

**Comment by andris9** [comment]
All the data is stored in MongoDB and Redis, so disaster recovery is basically getting databases back online or recovered. 

For Redis, run it in a Redis Sentinel configuration, so that when the primary node goes down, a replica is automatically promoted to master. Also, make periodic copies of the Redis data dump from the disk.

For MongoDB use a replica-set or shared cluster setup. So if the primary goes down, a replica picks up automatically. Also make periodic backups. If you don't have a large database, then you can go with the vanilla MongoDB and use `mongodump`. If you have a larger cluster, then I'd suggest looking into the Percona version of MongoDB as they have better backup tooling.

For config files etc, it would be better if you provision the config files using Ansible or something that you can easily replay later. WildDuck and ZoneMTA do not store anything on disk, so if you get the application files and configuration files back up, it should work without issues.
