### ISSUE TITLE
Unknown error. (TAG3 NO (TEMPFAIL) SELECT completed)

### ISSUE THREAD

**Issue by mleader1** [nodemailer/wildduck#378]
Hi there,

We are receiving this error on wildduck:

```
TAG3 NO [TEMPFAIL] SELECT completed
```

Can anyone give some light on the cause please?   is it MongoDb related query error?  Double checked Mongodb, healthily running...

Many thanks in advance

**Comment by andris9** [comment]
You should check the application logs to see if there are any error messages. This specific issue happens when WildDuck fails to run MongoDB commands in a given time to open a mailbox folder. It might be that the query failed for whatever reason. Or it might be that the query took too much time to finish so that WildDuck aborted the action. Without logs, it is difficult to say what's the exact reason.
