### ISSUE TITLE
WildDuck looks promising, but.......

### ISSUE THREAD

**Issue by smolinari** [nodemailer/wildduck#381]
Hi,

I've been searching for a email server for some time to support the system we are building (a specialized PaaS) and I've ended up here, because WildDuck fits many requirements we have. I just have some questions/ concerns, which I hope can be answered/ laid to rest.

1. We are interested in the containerized version of WildDuck, however, it looks like the WildDuck container isn't up-to-date (2 minor versions behind?). Is this correct? If yes, will the containers be updated? Why I ask, at some point, we would like to get WildDuck working within Kubernetes. We could offer our work with a k8s version back to the project. The cool thing is, WildDuck is running the exact same supporting technologies as our tech stack (i.e. Node/MongoDB/Redis). So, it's like a match made in heaven. 😁 What is interesting is the docker setup was updated 24 days ago. Yet, the container is still 8 months old?

2. No-SPOF - This is also a requirement we have. HA is extremely important to us. I think we can help make this claim even better with the k8s version. Just a note that the current docs don't offer a clear multi-node install path.  

3. Looking at the open issues and the PRs (especially from Snyk), this project has the impression of missing TLC and security isn't a priority (despite what the docs say). It's just an impression though. I know with OSS, one can't have a lot of expectations and I also do understand what kind of time investment is needed to make something like this possible, but part of winning people to use OSS is to have a quality solution. Nodemailer is huge (2M weekly downloads) and I realize that is also probably a lot of work, but looking at the world of OSS mail servers, none of them are HA OOTB and none are k8s ready (not really, despite one or two having helm charts, they are missing decent web APIs, which to me, is an absolute must for k8s use).

At any rate, I wish I could say I could help support this project even more, but we have our hands completely full building up the base system currently. I'm hoping for some positive words from a/the maintainer so we can have a bit more confidence to take on WildDuck as our email server of choice. Thanks for reading. 

Scott

**Comment by andris9** [comment]
WildDuck can be set up in a No-SPOF setup. The included install script does not do this, as the goal of that script is to get something up and running. For a No-SPOF setup, you have to set up MongoDB in a replicated (or better yet sharded) cluster and Redis in a [Redis Sentinel setup](https://redis.io/topics/sentinel) (WildDuck does not support Redis Cluster). You can then add and remove individual apps as you like. All of the apps (Haraka MX, ZoneMTA MTA, WildDuck IMAP/POP3/API) are stateless, so you can take these down any time you like or add new or additional instances - all you have to do is to figure out routing so that you would reach these hosts.

The vulnerabilities listed on [Snyk](https://snyk.io/test/npm/wildduck/1.36.2) do not affect WildDuck as the vulnerable code paths are not used. Some will be "fixed" automatically with a new release by a version bump (qrcode). Some have significant API changes and do not get automatic upgrade bump (jsrsasign). It's a bummer to have a vulnerability listed but spending a lot of time reimplementing features only to get a checkmark in vulnerability scanning is not a great way to spend time.

Container support does have its issues. I, as the main developer on WildDuck do not use Docker at all. We run WildDuck in physical servers as SystemD services, so everything related to Docker is a community effort. Docker hub does not auto-build containers anymore for free accounts, and no one has had time to convert it to use Github Actions instead. This is why those images are outdated.

For background, WildDuck was mainly built for a specific single company ([Zone.ee](https://www.zone.ee/en/web-hosting/premium-email/)) and has been maintained as such. Open-sourcing WildDuck was kind of a side effect, as I built WildDuck on top of my [previous IMAP projects](https://github.com/andris9/hoodiecrow) so it made sense keeping WildDuck open as well. The good thing is that WildDuck is maintained for the foreseeable future. The bad thing is, as I'm mainly driven by the needs of the major sponsor, I've been focusing on the pain points they have and have not really spent time on making this a good open source project.

**Comment by andris9** [comment]
PS. WildDuck "lives" under the nodemailer "organization" in Github because at that time the Nodemailer org was put to a pro plan by Github for free. WildDuck has actually no relations to [nodemailer.com](https://nodemailer.com/) except that I'm the author of both of these projects. At first, I used a different Github org for WildDuck but wanted to use the pro features, so moved all the repos over to the Nodemailer org.

**Comment by smolinari** [comment]
Ok. Thanks for the explanation. I appreciate it. I'm a bit more at ease with taking on WildDuck and certainly thank you for your efforts, as I can respect the complexity of putting together a mail server like this, especially one that is set up for HA. 

Just to get things going for us, we'll more than likely fire up a VPS and install WildDuck with the given installer. Maybe I can take a look at the container building in a couple of weeks. I can't promise that though. 

One thing I can almost bet is that if WildDuck could also be set up to work in k8s, it would fill a gap in the market. Not sure if that in anyway piques your interest.

On the Snyk PRs, maybe they could be closed, if they aren't important to the package? Not a biggy, but it might help with first impressions. 😁 

Nodemailer is a very popular package. Hope your getting returns for that work in some way. 

Thanks again!

Scott

**Comment by smolinari** [comment]
Oh. Btw, I wanted to try out the demo, but it fails when trying to add a new account. 

Scott

**Comment by andris9** [comment]
> Oh. Btw, I wanted to try out the demo, but it fails when trying to add a new account.
> 
> Scott

I think this happens when you use a username that's already been registered, for whatever reason it fails to show the error message about it. Try to come up with something unique.

**Comment by andris9** [comment]
I meant that use a unique username. There are ton's of accounts registered, so whatever you try to use might not be available, but the error messages gets lost somehow

**Comment by smolinari** [comment]
Ok. I'm in. Thanks. 

As I'm learning, DuckyPanel has the actual API we'd be interested in (with domain management). Still, it is promising that all this is sort of already done (to a point) and not another project we need to tackle from the ground up! Looking forward to seeing if we can get everything running to be able to either test or even help out with either project. 

Thanks again!

Scott

**Comment by andris9** [comment]
Domain management not being part of the WildDuck API has been a conscious decision. Instead, you can group users by tags. The reason was that different organizations have different methods to group users, so yeah, you either need something like DuckyPanel to manage grouping by domains or you do this by yourself with `tags` and `internalData` values. For example when creating email accounts you can assign a tag like `"account:12345"` where `12345` is the ID for the client account and then you can list all email accounts for that client by running `/users?requiredTags=account:12345`

**Comment by randrusiak** [comment]
I also consider wildduck as a great solution for our internal project. I can help with containers and releasing stuff, but I'm a little worried that it seems you stop using semver (the last version was published 6m ago) and there is no changelog. 

Currently, docker images are published with sha hashes which in my opinion look messy. Without semantic versioning (or other methods) is hard to make sure that the new version doesn't contain breaking changes.
