### ISSUE TITLE
Apple Mail Desktop no SMTP via mobileconfig

### ISSUE THREAD

**Issue by NicolaiSchmid** [nodemailer/wildduck#389]
Hello,
I've setup wildduck and added an account via the mobile config feature to both my iPhone and my Apple Mail for desktop. On the phone, everything works well, however, on the desktop there seems to be an issue with configuring the SMTP server. Fetching emails via IMAP works fine, but the mobileconfig (the same as for the phone) doesn't seem to register the SMTP server. 
Looking inside the file, the server and its configuration are present, and of course it's too working on the phone. 
I'm quite struggling with this issue because I don't know how to debug it. 
The server works fine with other clients (Thunderbird, Outlook, iPhone Apple Mail)

Do you have any ideas where I should look, what logs I should monitor to narrow this issue down?

I appreciate any ideas you might have!

**Comment by andris9** [comment]
Can you add the same server settings manually? Does it work then?

**Comment by NicolaiSchmid** [comment]
Adding it manually (without ports, just the domains) leads to a _very_ long load and an eventual error "Unable to verify account name or password".

Adding ports lets it verify immediately (successfully) only to not save the credentials and display the server as offline in the account settings.  
When I add the username back in the settings, it verifies immediately, but returns the same credential error as above.

So, when only looking at Apple mail, with the mobile config, it adds it quickly and only IMAP works (on desktop), adding it manually doesn't work at all

**Comment by NicolaiSchmid** [comment]
?

**Comment by msimerson** [comment]
The Mail payload in the `.mobileconfig` is not being populated correctly.

I definitely have the settings correct in my wildduck config:

<img width="560" alt="Screenshot 2024-03-29 at 9 43 57 PM" src="https://github.com/nodemailer/wildduck/assets/261635/6d3e18e1-c9fa-4e6f-ad65-afe099b6a3d1">

And yet, if you inspect the attached mobileconfig file, you'll see the Outgoing Mail Server is `localhost` and the port is `2587`.  (Fear not, the password in the file is no longer active).

--- 

[matt.mobileconfig.zip](https://github.com/nodemailer/wildduck/files/14810387/matt.mobileconfig.zip)

**Comment by NicolaiSchmid** [comment]
> you'll see the Outgoing Mail Server is localhost and the port is 2587
For me, that's not the issue. It sets the`OutgoingMailServerHostName` correctly, but my described issue above still persists

**Comment by louis-lau** [comment]
@msimerson You haven't posted the mobileconfig configuratie of wildduck that you say you've set correctly. No way for us to know if it is. Wildduck webmail wouldn't use the mobileconfig settings to display that page.

@NicolaiSchmid Sorry, but I don't think we can help from a distance. It sounds like an issue with your apple mail instance, not wildduck or zonemta. Look at the zonemta logs or debug the client instead of the server.

**Comment by msimerson** [comment]
> You haven't posted the mobileconfig configuration of wildduck....Wildduck webmail wouldn't use the mobileconfig settings to display that page.

Oh boy, I've run aground on *another* assumption. In the `wildduck-webmail/config/default.toml` are these settings:

```toml
[setup]
    # these values are shown in the configuration help page
    [setup.imap]
        hostname="mail.tnpi.biz"
        secure=true
        port=993
    [setup.pop3]
        hostname="mail.tnpi.biz"
        secure=true
        port=995
    [setup.smtp]
        hostname="mail.tnpi.biz"
        secure=false
        port=587
```

which are displayed in the account help page. I **assumed** those values would also be used to generate the .mobileconfig file. I have since been disabused of that notion.

This was insightful: `wildduck/config # grep mobileconfig *`

In the wildduck/config/wildduck.toml file, I have:

```toml
[smtp.setup]
# Public configuration for SMTP MDA, needed for mobileconfig files
hostname = "mail.tnpi.biz"
secure = false
port = 587
```

I had also **assumed** (prior to reading the docs for `wild-config`) that wildduck.toml would take precedence over `wildduck/config/default.toml`, but I now understand that it does not. [The setup script](https://github.com/nodemailer/wildduck/blob/master/setup/07_install_wildduck.sh) **moves** config.toml to wildduck.toml. Now I realize _why_ that file is **moved** and not copied. 😮‍💨

After replacing default.toml with my customized wildduck.toml file, the mobileconfig settings in `wildduck/config/api.toml` and `wildduck/config/default.toml` are reflected in the .mobileconfig file.

I smell a new wiki page coming...

I presume there's a good reason to have the `[smtp|pop3|imap.setup]` sections in `wildduck/config/*` and then essentially duplicate those settings in the wildduck-webmail config?

I was thinking perhaps wildduck-webmail was designed to be more easily branded, so you could run virtual instances for different brands. But if the .mobileconfig settings are pulled from wildduck configs, that wouldn't work so well.

**Comment by louis-lau** [comment]
Wildduck webmail just uses the wildduck api, it's a seperate application and an example of what you can build on top of wildduck.

**Comment by NicolaiSchmid** [comment]
> Sorry, but I don't think we can help from a distance. It sounds like an issue with your apple mail instance, not wildduck or zonemta. Look at the zonemta logs or debug the client instead of the server.

I can confirm the issue also persists on the webmail.wildduck.email instance (i just signed up and downloaded the configuration profile), not only on my Mac (and for the last two years, across software updates) but also on a friend's macbook
<img width="576" alt="image" src="https://github.com/nodemailer/wildduck/assets/12787309/c651f36d-0ad9-441f-99d6-6ddbc4090e4b">

**Comment by msimerson** [comment]
Since my issue was not related this this thread and felt a little like issue hijacking, I've deleted my posts.

**Comment by louis-lau** [comment]
> I can confirm the issue also persists on the webmail.wildduck.email instance

SMTP doesn't seem exposed on the demo instance. If you try to `telnet wildduck.email 587` you'll see that you're not able to connect.

@andris9 The banner says "Messages from SMTP and webmail are queued but not delivered". Should this be updated, or should smtp submission be exposed?

This doesn't explain why something is not working on your instance, if you were to provide some more info that would be very helpful! Apple mail has a built-in connection doctor for example. Or perhaps provide the generated mobileconfig file with the app password redacted? Otherwise, screenshots of your manual settings? What about the mobileconfig toml configuration in wildduck?

The reason this has gone unanswered for so long is because it's not easily reproducible on a properly set up server, and there isn't enough information provided for us to be of any help. I do understand you asked for debugging steps, but it's hard for open source maintainers to play free support monkey if you understand what I mean :). Hopefully going over the things I mentioned above help you debug the issue.

**Comment by NicolaiSchmid** [comment]
Thanks for your reply! 
I will post all of the above within the next week or two! 
I appreciate your help! 🙏
