### ISSUE TITLE
ActiveSync

### ISSUE THREAD

**Issue by andris9** [nodemailer/wildduck#39]
Could be added in the future. Looked though the spec and found nothing that would not be doable.

http://interoperability.blob.core.windows.net/files/MS-ASHTTP/%5BMS-ASHTTP%5D.pdf

**Comment by andris9** [comment]
Building entire ActiveSync stack would probably be too much work for now. As a shortcut [Z-Push](http://z-push.org/) could be used as it supports custom backend as well.

**Comment by louis-lau** [comment]
I've never tried it, but as far as I know you could use z-push right now.

I _have_ tried activesync through SoGO, and I'll tell you that IMAP/CALDAV/CARDDAV was a lot more stable. Of course I'm not sure if this was actually just because of SoGO, and not because of the protocol. I've heard similar things about Z-push though.
