### ISSUE TITLE
wild duck server is running but there is nothing on localhost:3000

### ISSUE THREAD

**Issue by Amirzvni** [nodemailer/wildduck#449]
Hello
i'm trying to run wildduck locally on mac , i started it with :
node server.js
<img width="1082" alt="Screenshot 2023-02-14 at 3 28 59 PM" src="https://user-images.githubusercontent.com/98328997/218732096-d9a3a045-a5f9-441a-98a0-12029ef78082.png">
but there is nothing on my localhost:3000 
<img width="859" alt="Screenshot 2023-02-14 at 3 30 19 PM" src="https://user-images.githubusercontent.com/98328997/218732523-40584ad8-c2ab-4f90-a38c-9c98e28ddf8b.png">
also my localhost:8080 is like this : 
<img width="454" alt="Screenshot 2023-02-14 at 3 30 39 PM" src="https://user-images.githubusercontent.com/98328997/218732614-46e79071-aa6e-49bc-bbdc-c79b5d1b656c.png">

**Comment by louis-lau** [comment]
This looks like I'd expect. Nothing runs on port 3000, and the api on port 8080 doesn't have an endpoint on `/`. Is there something you expected to see?

**Comment by Amirzvni** [comment]
> 



> This looks like I'd expect. Nothing runs on port 3000, and the api on port 8080 doesn't have an endpoint on `/`. Is there something you expected to see?

i want to send and recieve emails locally and basiclly im trying to figure out how to do that with wild duck
i read the documentation but i couldnt understand how to do so
any help would be appreciated

**Comment by louis-lau** [comment]
Wildduck itself is only an IMAP server and an API. For incoming email you'll need haraka + the wildduck plugin. For outgoing email you'll need zone-mta + the wildduck plugin. If you want to access it in your browser you'll need a webmail. That can be wildduck-webmail or another project like roundcube.

The setup script in this repo sets that all up for you. I recommend you run that in a local or cloud Linux VM to try out wildduck. Otherwise you will have to set everything up yourself.

**Comment by louis-lau** [comment]
Note the 2 sections here. "Complete mail server" and "wildduck only". I think you followed the wildduck only instructions.
https://docs.wildduck.email/#/general/install
