### ISSUE TITLE
mutli domain configuration / documentation

### ISSUE THREAD

**Issue by chrisjsimpson** [nodemailer/wildduck#47]
Thanks for working on such an excellent project. 

This may be a question more regarging ZoneMTA as it covers both delivery and storage.  

How would one configure wildduck for multi domain usage, is this something I can try and help with? If so, I'd appreciate being pointed in the right direction. I'm guessing this won't work 'out the box'.

Would if be a case of setting [senderDomains](https://github.com/zone-eu/zone-mta#routing-based-on-sender-domain-name) somewhere in Wildduck config? Or in `/opt/zone-mta/config/domains.toml`?

On a traditional postfix install we have multiple `virtual_mailbox_domains` set, and then use [opendkim](http://opendkim.org/) for DKIM signing. Finally Docecot used to store in a /data/%d /%n  (%d = domain) (%u = user) type fashion.

**Comment by andris9** [comment]
WildDuck is domain name agnostic, all it cares about are addresses. The default web interface installed with install script supports only a single domain but this is so because the UI was easier to implement that way. If you look at the [Wild Duck API](https://api.wildduck.email/#api-Users-PostUser) and perform the calls directly then there are no limitations about domain name use. If you create an address for user@domainX and then point MX of domainX to WildDuck then that is all you need to do.

```
curl -i -XPOST http://localhost:8080/users \
-H 'Content-type: application/json' \
-d '{
  "username": "myuser",
  "password": "verysecret",
  "name": "John Doe",
  "address": "user@whateverdomain"
}'
```

**Comment by andris9** [comment]
Oh, and domain specific DKIM keys are a future feature. The ZoneMTA WildDuck plugin is going to handle it in the future, for now you'd have to share the same key between all domains.

**Comment by chrisjsimpson** [comment]
Thank you @andris9
