### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by fnpac** [nodemailer/wildduck#51]
https://github.com/nodemailer/wildduck/blob/f9844306ad3a9ad28b7c48fb125a25afc616279d/lib/message-handler.js#L466

because of queryOpts, messageData.mailbox is always Undefined, so i think `mailbox: mailboxData._id` will be better. as `_id: messageData._id` is Unique, so this line also can delete.

**Comment by andris9** [comment]
Fixed in 06ad073769493f75ab828c1bc1da4eabf8cc86fd

_id is unique and it is also primary key, so Mongo optimises to use IDHACK plan and ignores the other options when looking up the entry. These extra values are needed for sharding as shard key is `{mailbox, uid}`. So _id is unique but without the shard key Mongo would not know from which shard to look for the _id.
