### ISSUE TITLE
Possible bug - `onCopy` handler does not check for `user` on mailbox find

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#517]
I think that there is a missing query property of `user` in the query here:

<https://github.com/nodemailer/wildduck/blob/be900691dab73f126b9429a8d6da2c43739f3f16/lib/handlers/on-copy.js#L39-L46>

Otherwise any user could arbitrarily query for a mailbox by an ID not associated to their given user ID (?)

```diff
    let mailboxData = await db.database.collection('mailboxes').findOne(
        {
-            _id: mailbox
+            _id: mailbox,
+            user: userData._id
        },
        {
            maxTimeMS: consts.DB_MAX_TIME_MAILBOXES
        }
    );
```

cc @andris9

**Comment by andris9** [comment]
The mailbox ID comes from a session value that was previously resolved from the active path. The user can not set this value.

```
X SELECT ABC
  -> ABC is resolved to 12345
  -> this.session.mailbox is set to 12345
X COPY 123 DFG
  -> onCopy(this.session.mailbox,..., "DFG")
  -> source folder uses this.session.mailbox value
  -> destination folder is resolved using {user, path}
```

**Comment by andris9** [comment]
Yes, this is unfortunate. The COPY action is accepted as a whole, so either all messages get copied, or none get copied. So WildDuck allows copying as long as there is some free quota. So, the maximum space it can use is 200% of the allowed quota (copying all messages if you have 1 byte of quota remaining), which is acceptable.

Email clients almost never copy but run copy+expunge instead of moving messages, so in most cases, the copied emails get deleted from the source mailbox almost immediately anyway. Actively blocking copy operations in these situations would crash email clients. Imagine the following situation: quota is full, and the user tries to delete messages from Inbox but can't do this because the email client tries to move the messages to the Trash folder, and this operation fails because there is not enough quota available.
