### ISSUE TITLE
Feature request: onOpen handler could use `distinct` instead of `find` (performance gain?)

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#530]
This may be a subtle performance gain (for huge payloads), but you could perhaps use `distinct` instead of `find` to get all the distinct `uid` values, and thus not have to do `new Set` and `Array.from` nor the projection.  Instead you could simply do a sort.

<https://github.com/nodemailer/wildduck/blob/fed3d93f7f2530d468accbbac09ef6195920b28e/lib/handlers/on-open.js#L37-L52>

**Comment by andris9** [comment]
The client-side sorting is intentional. The result list can be very large, and asking for the server to sort it would end up in large memory usage for loading sorting indexes and a potential response error if the result set is too large.

Distinct has a limited response size. The folder could include hundreds of thousands of emails, and using distinct (basically, an aggregation method) would end up with a response error.
