### ISSUE TITLE
Bug: imaptest results and issues

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#536]
We ran a local test of Dovecot's `imaptest` against WildDuck and saw that (besides the ones listed at the below link), there were a few size changes (e.g. +/- a few bytes).  Assuming this is due to CRLF / line return changes  (?) should we mention this in the docs too (at below link)?

```sh
Error: test@test.com[2475]: uid=2010 3FBE2D8D.9030507@jokes.dk: RFC822.SIZE size changed 3629 -> '3627': * 3 FETCH (UID 2010 RFC822.SIZE 3627 BODYSTRUCTURE ("TEXT" "PLAIN" ("CHARSET" "ISO-8859-1" "FORMAT" "flowed") NIL NIL "8BIT" 1500 48 NIL NIL NIL NIL))
```

<https://github.com/nodemailer/wildduck/blob/73acc42cd19af0e9fd0703d5306838f7ac5c9f17/docs/in-depth/protocol-support.md?plain=1#L25-L27>

**Comment by louis-lau** [comment]
At the bottom of that page is this:
> Messages retrieved from WildDuck might not be exact copies of messages that were initially stored. This mostly affects base64 encoded attachments and content in multipart mime nodes (eg. text like "This is a multi-part message in MIME format.")

I can't be sure, but this could be the reason for the difference in size?

**Comment by andris9** [comment]
It's more or less a non-issue. All email clients would use this value as a string `"imaptest/%"` (which would not throw), not as an atom `imaptest/%`. Both are correct, but the WIldDuck's IMAP parser does not recognize the context – in general, `%` is not allowed in an atom value, but this is a special mailbox wildcard specifier, and in this specific occasion (but otherwise, not), it should be allowed. If I'd see that a real email client, that people actually use, would also have this issue, then I'd consider fixing it. Right now, with IMAPtest, it is not very important.
