### ISSUE TITLE
Bug: Duplicate Message-ID's can be appended to same mailbox path (unlike Gmail which detects Message-ID)

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#555]
It is said that WildDuck tries to follow Gmail design, but one thing it is missing is that in `APPEND` duplicate Message-ID `msgid` values can get appended to the same mailbox path.  Just filing this issue here so you are aware.

**Comment by louis-lau** [comment]
Sounds like a feature request though, not a bug :)

**Comment by andris9** [comment]
The earlier versions of WildDuck did this, and it resulted in a huge number of issues. Turns out email clients are pretty liberal on how to treat Message-Id values. For example, when sending emails, some email clients might use value X as the Message-ID that was sent to SMTP, but value Y as the Message-ID for the message uploaded to the Sent Mail folder via IMAP. Email clients also often use email servers for backends for arbitrary data, like Notes etc, and these entries might not have a Message-ID set at all. Gmail uses some advanced logic to determine what is what.
