### ISSUE TITLE
Docs: `CHARSET` not supported in search (should we add to docs?)

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#562]
As described in title, SEARCH does not support CHARSET yet as per <https://datatracker.ietf.org/doc/html/rfc9051#section-6.4.4-1.2.2>.  Should we add to the docs about this at https://github.com/nodemailer/wildduck/blob/master/docs/in-depth/protocol-support.md#e-mail-protocol-support?

**Comment by andris9** [comment]
The linked RFC is about IMAP v4rev2, WildDuck supports v4rev1, so you should look at RFC3501 instead. But otherwise, yes, WildDuck ignores the CHARSET modifier and treats all strings as UTF8.

Is this something you stubled upon, eg some email client was trying to search for messages using a non-UTF8 charset?

**Comment by andris9** [comment]
Yes, in this regard it is a valid deviation an could be included in the list.
