### ISSUE TITLE
Core Bug: `Cannot read properties of undefined (reading 'toUpperCase')`

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#618]
If `node.type` is undefined, then an uncaught exception is thrown.

<https://github.com/nodemailer/wildduck/blob/3d864c87debabe5494c6bfabb2d406949bb264a2/imap-core/lib/handler/imap-compile-stream.js#L149>

**Comment by andris9** [comment]
How do you have a Date object as the node? This is not a supported value for the response compiler.

**Comment by andris9** [comment]
Thanks for the explanation. I'd prefer less magic here, and I think it is good to have an exception when parsing internal structures with expected values - helps to detect problems sooner. I'd also suggest not labelling issues as "core bugs" unless you have a reproducible test case, otherwise the issue can be overlooked even if it identifies a real problem.
