### ISSUE TITLE
Bug: `EXPUNGE` written to stream twice when only should be done once

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#697]
As you can see from the logic here, for a `MOVE` command, both conditionals will be satisfied as `true`:

<https://github.com/nodemailer/wildduck/blob/c9188b3766b547b091d140a33308b5c3ec3aa1d4/lib/message-handler.js#L1074-L1090>

`options.session` will be an Object and `options.showExpunged` will be `true` as per this:

<https://github.com/nodemailer/wildduck/blob/c9188b3766b547b091d140a33308b5c3ec3aa1d4/lib/handlers/on-move.js#L38-L42>

**Comment by andris9** [comment]
The first EXPUNGE does seem to be extraneous. I wonder, though, how did you manage to trigger it, as the `formatResponse` method should be no-op with these arguments and never write anything. If I try to move messages with WildDuck I get the second EXPUNGE (` if (options.showExpunged)` printed out but never the first (`if (options.session)`) because arguments are not valid.
