### ISSUE TITLE
Feat: Add support for `XAPPLEPUSHSERVICE`

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#711]
## Hi folks 👋   We're the team that made **[Forward Email](https://forwardemail.net)**, the only 100% open-source email service out there.

👉 Check it out at https://forwardemail.net!!! 👈 

Keep reading below for insight into how we implemented iOS Push support! ⏬ 

> P.S. Try using coupon code `GITHUB` for a discount 😉 

Ref: <https://docker-mailserver.github.io/docker-mailserver/latest/examples/use-cases/ios-mail-push-support/>

**Comment by louis-lau** [comment]
I agree this would be very nice to have! May not be that easy, as there's no publically available official spec.

**Comment by louis-lau** [comment]
Nice! The fact that people have reverse engineered this before should make things easier. Looking into this was on my list somewhere, but there's about 999 things above it haha. Good luck!

**Comment by JDENredden** [comment]
I can’t contribute anything technically, but I would love to see this implemented. Major quality of life win for iOS users.

**Comment by JDENredden** [comment]
Mailbox.org is another one that has managed to make push email work on iOS. They’re another one to reach out to. Zoho Mail rely on ActiveSync to do push on iOS. On 1 Aug 2024, at 8:39 am, titanism ***@***.***> wrote:﻿
Okay so despite it working and the APN being successfully delivered – it doesn't appear that APPL is accepting it for delivery to the device/account pair.  I've reached out to folks at APPL, Linux (maintainers of that Dovecot project), and the team at Fastmail.  Hoping we can figure out if this is possible still or not, and if not, what are the alternatives.  It seems that Yahoo and Fastmail can only do this approach because of a custom licensing that permits them for com.apple.mobilemail push notifications.

**Comment by gctwnl** [comment]
I've just found this thread (as I ran into this trying my yearly renewal on OS X Server.

I have an OS X Server license (a running Mac mini server with High Sierra and Server.app) but Server.app is no longer capable of renewing the cert. I already have (via MacPorts on macOS) a Dovecot running that does iOS Push. The only thing I need is an updated cert. Is there a script somewhere that can help me with that?

**Comment by louis-lau** [comment]
@gctwnl https://github.com/freswa/dovecot-xaps-daemon/issues/43

**Comment by gctwnl** [comment]
> [@gctwnl](https://github.com/gctwnl) [freswa/dovecot-xaps-daemon#43](https://github.com/freswa/dovecot-xaps-daemon/issues/43)

Yes, thank you, I have seen that one. What I could not learn from it was how to do my cert renewal if Server.app on High Sierra doesn't work (because of certificate errors?).

I've read a lot of other threads too and this was the only one where I found statements that (a) renewal works and (b) the certs work for APNS and the push notifications arrive at the devices. So. I had lost most hope, but now I see it must be possible. I just don't know yet _how_ exactly in my situation.

**Comment by louis-lau** [comment]
> but now I see it must be possible

Where? The messages here are older than in the issue I linked.

**Comment by gctwnl** [comment]
> > but now I see it must be possible
> 
> Where? The messages here are older than in the issue I linked.

You are right, that was in this thread. I had so many open that were related I got confused. Sorry. This is the one that says it worked. But I still have no idea how to perform the cert renewal without a working Server.app (which returns error -80010 because of apparently cert/keychain issues)

**Comment by louis-lau** [comment]
Yeah, it worked in August at least, but I think dovecot-xaps-daemon worked then as well. To my knowledge, everyone uses the exact same endpoint, reverse engineered from Server.app. Fastmail probably has another endpoint, or they have a cert with a long lifetime. But none of it is public. As far as I can see, there currently is just no way. So unless Apple changes something, this functionality will be dead.

**Comment by thefl0yd** [comment]
yes, correct. It first broke around early / mid November of 2024 and then for a very short time Apple must have turned the endpoint back on because I was able to sneak in and get a renewal mid/late November. Since then nobody has successfully gotten a renewal. Fastmail is the only known place this works and only Apple can give us a mechanism to re-implement this. Unless that happens it seems we're dead in the water.

The only 'open' way to re-implement this functionality is for someone to write an iOS email client that supports this push mechanism and update the daemon and dovecot setup to use those topics (as the app bundle would have its own topic which we can create/renew certs for).

**Comment by andris9** [comment]
It is not exactly a replacement, but I have used https://docs.ntfy.sh/subscribe/phone/ with EmailEngine to send notifications about new emails, etc, to my phone.

**Comment by securechicken** [comment]
Other projects are affected by the same problem (https://github.com/st3fan/dovecot-xaps-daemon/issues/58, https://github.com/freswa/dovecot-xaps-daemon/issues/43, https://github.com/matthewpowell/pushnotify/issues/5, https://github.com/mailcow/mailcow-dockerized/issues/6322, https://github.com/orgs/docker-mailserver/discussions/3432, https://github.com/stalwartlabs/mail-server/issues/747): Apple basically patched the only hack that third party FOSS developers used.

Here is the current state of play as of today: one freswa/dovecot-xaps-daemon contributor (@DragonWork) posted a request on Apple Developers forums late March 2025, asking Apple how should such interoperability issue could and should be faced. This request on Apple Developers forums will benefit from upvotes/boost/testimonials from other FOSS contributors and maintainers.

**Comment by titanism** [comment]
iOS push is still working just fine here at https://forwardemail.net - and we recently added iOS push support to calendars and contacts as well without issue (this past few days).  Certs still working just fine, everything is open-source on our GitHub @forwardemail.

https://x.com/fwdemail/status/2054104194315948177

Fastmail also mentions it here https://www.fastmail.com/blog/push-sync-for-contacts-calendars-now-available-on-ios/

> Just so you’re aware, the iOS Settings may not show “Push” as enabled for contacts, however the push still works just fine! We hope this minor bug will be fixed in a future iOS update.
